import type { Request, Response, Router } from "express";
import type { Env } from "../env";
import type { DiagramSpec } from "@aud/types";
import {
  saveDiagramSpec,
  getDiagramSpec,
  listDiagramSpecs,
  buildLiveSnapshot,
} from "../services/liveAggregator";
import {
  mockDiagramSpec,
  generateMockSnapshot,
} from "../services/liveDiagramMock";
import { tryGetArchitectureGraphFromAzure, clearGraphCache } from "../services/azure";
import { generateDiagramSpec } from "../services/specGenerator";
import { fetchEdgeNetworkDetail } from "../services/edgeDetailService";

// Seed the mock diagram on startup
saveDiagramSpec(mockDiagramSpec);

export function registerLiveDiagramRoutes(router: Router, env: Env) {
  // ── List all diagrams ──
  router.get("/api/live/diagrams", (_req: Request, res: Response) => {
    res.json({ diagrams: listDiagramSpecs() });
  });

  // ── Get a single diagram spec ──
  router.get("/api/live/diagrams/:id", (req: Request, res: Response) => {
    const spec = getDiagramSpec(req.params.id);
    if (!spec) {
      res.status(404).json({ error: "Diagram not found" });
      return;
    }
    res.json({ diagram: spec });
  });

  // ── Auto-generate diagram from Azure Resource Graph ──
  // IMPORTANT: Register before generic POST /api/live/diagrams to avoid route conflicts
  router.post("/api/live/diagrams/generate", (req: Request, res: Response) => {
    const subscriptionId =
      typeof req.body?.subscriptionId === "string"
        ? req.body.subscriptionId
        : undefined;

    // Always clear graph cache on generate to ensure fresh Azure data
    // with latest edge extraction logic
    clearGraphCache();

    tryGetArchitectureGraphFromAzure(env, req.auth?.bearerToken, {
      subscriptionId,
    })
      .then(async (graph) => {
        if (!graph) {
          // Azure Resource Graph not available — fall back to mock diagram with demo traffic
          const spec = { ...mockDiagramSpec, id: "auto-demo", name: "Demo Infrastructure" };
          spec.updatedAt = new Date().toISOString();
          saveDiagramSpec(spec);
          res.status(201).json({ ok: true, diagram: spec, _source: "mock" });
          return;
        }

        const subId = subscriptionId ?? env.AZURE_SUBSCRIPTION_IDS?.split(",")[0] ?? "default";
        const { spec, containmentDiagnostics } = await generateDiagramSpec(graph, subId);
        saveDiagramSpec(spec);
        const nodesWithParent = spec.nodes.filter(n => n.parentId).length;
        const groupNodesList = spec.nodes.filter(n => n.nodeType === "group");

        // ── Verification logs (user requirement #4) ──
        const vnetCount = spec.nodes.filter(n => n.icon === "vnet").length;
        const subnetCount = spec.nodes.filter(n => n.icon === "subnet").length;
        const nicCount = spec.nodes.filter(n => n.icon === "nic").length;
        const vmCount = spec.nodes.filter(n => n.icon === "vm").length;

        const subnetSamples = spec.nodes
          .filter(n => n.icon === "subnet")
          .slice(0, 5)
          .map(n => ({ id: n.id, parentId: n.parentId ?? null, label: n.label }));

        const nicSamples = spec.nodes
          .filter(n => n.icon === "nic")
          .slice(0, 5)
          .map(n => ({
            id: n.id,
            parentId: n.parentId ?? null,
            label: n.label,
          }));

        res.status(201).json({
          ok: true,
          diagram: spec,
          _source: "azure",
          _diagnostics: {
            graphNodes: graph.nodes.length,
            graphEdges: graph.edges.length,
            specNodes: spec.nodes.length,
            specEdges: spec.edges.length,
            nodesWithParent,
            groupNodes: groupNodesList.length,
          },
          _containment: containmentDiagnostics,
          _verification: {
            counts: { vnetCount, subnetCount, nicCount, vmCount },
            subnetSamples,
            nicSamples,
          },
        });
      })
      .catch((err: unknown) => {
        const msg = err instanceof Error ? err.message : "Unknown error";
        res.status(500).json({ error: msg });
      });
  });

  // ── Save/update a diagram spec ──
  router.post("/api/live/diagrams", (req: Request, res: Response) => {
    const body = req.body as DiagramSpec;
    if (!body?.id || !body?.version) {
      res.status(400).json({ error: "Invalid diagram spec: id and version required" });
      return;
    }
    body.updatedAt = new Date().toISOString();
    if (!body.createdAt) body.createdAt = body.updatedAt;
    saveDiagramSpec(body);
    res.status(201).json({ ok: true, id: body.id });
  });

  // ── Live snapshot (REST polling) ──
  router.get("/api/live/snapshot", (req: Request, res: Response) => {
    const diagramId = typeof req.query.diagramId === "string" ? req.query.diagramId : "prod-infra";
    const isAutoGenerated = diagramId.startsWith("auto-");

    // Always use buildLiveSnapshot for auto-generated diagrams (has simulated traffic)
    if (env.AZURE_LIVE_DIAGRAM_ENABLED || isAutoGenerated) {
      buildLiveSnapshot(env, req.auth?.bearerToken, diagramId)
        .then((snapshot) => {
          if (snapshot && hasRealData(snapshot)) {
            res.json(snapshot);
          } else if (isAutoGenerated && snapshot) {
            // Auto-generated diagrams with simulated traffic
            res.json(withSource(snapshot, "mock"));
          } else {
            // Aggregator returned empty data — fall back to mock
            res.json(withSource(generateMockSnapshot(), "mock"));
          }
        })
        .catch((err: unknown) => {
          const msg = err instanceof Error ? err.message : "Unknown error";
          res.json(withSource(generateMockSnapshot(), "mock", msg));
        });
    } else {
      // Mock mode — no Azure calls
      res.json(withSource(generateMockSnapshot(), "mock"));
    }
  });

  // ── SSE stream (server-push) ──
  router.get("/api/live/stream", (req: Request, res: Response) => {
    const diagramId = typeof req.query.diagramId === "string" ? req.query.diagramId : "prod-infra";
    const isAutoGenerated = diagramId.startsWith("auto-");
    const spec = getDiagramSpec(diagramId);
    const intervalSec = spec?.settings.refreshIntervalSec ?? 30;

    res.writeHead(200, {
      "Content-Type": "text/event-stream",
      "Cache-Control": "no-cache",
      Connection: "keep-alive",
      "X-Accel-Buffering": "no",
    });

    const sendSnapshot = () => {
      if (env.AZURE_LIVE_DIAGRAM_ENABLED || isAutoGenerated) {
        buildLiveSnapshot(env, req.auth?.bearerToken, diagramId)
          .then((snapshot) => {
            const data = snapshot && hasRealData(snapshot)
              ? snapshot
              : (isAutoGenerated && snapshot)
                ? withSource(snapshot, "mock")
                : withSource(generateMockSnapshot(), "mock");
            res.write(`data: ${JSON.stringify(data)}\n\n`);
          })
          .catch(() => {
            res.write(`data: ${JSON.stringify(withSource(generateMockSnapshot(), "mock"))}\n\n`);
          });
      } else {
        res.write(`data: ${JSON.stringify(withSource(generateMockSnapshot(), "mock"))}\n\n`);
      }
    };

    sendSnapshot();
    const timer = setInterval(sendSnapshot, intervalSec * 1000);

    req.on("close", () => {
      clearInterval(timer);
    });
  });

  // ── Edge Network Detail (on-demand, 30s cached) ──
  router.get("/api/live/edge-detail", (req: Request, res: Response) => {
    const diagramId = typeof req.query.diagramId === "string" ? req.query.diagramId : "prod-infra";
    const edgeId = typeof req.query.edgeId === "string" ? req.query.edgeId : "";
    if (!edgeId) return void res.status(400).json({ error: "edgeId_required" });

    fetchEdgeNetworkDetail(env, req.auth?.bearerToken, diagramId, edgeId)
      .then((data) => res.json(data))
      .catch((e: unknown) => {
        res.status(500).json({ error: e instanceof Error ? e.message : "edge_detail_error" });
      });
  });

  // ── Data source status ──
  router.get("/api/live/status", (_req: Request, res: Response) => {
    res.json({
      azureEnabled: env.AZURE_LIVE_DIAGRAM_ENABLED,
      appInsightsConfigured: !!env.AZURE_APP_INSIGHTS_APP_ID,
      oboConfigured: !!(env.AZURE_AD_TENANT_ID && env.AZURE_AD_CLIENT_ID && env.AZURE_AD_CLIENT_SECRET),
      trafficSources: {
        trafficAnalytics: env.AZURE_TRAFFIC_ANALYTICS_ENABLED && !!env.AZURE_LOG_ANALYTICS_WORKSPACE_ID,
        nsgFlowLogs: !!env.AZURE_NSG_FLOW_LOG_STORAGE_ACCOUNT,
        appInsightsDependencies: !!env.AZURE_APP_INSIGHTS_APP_ID,
        connectionMonitor: env.AZURE_CONNECTION_MONITOR_ENABLED,
      },
      cacheTtl: {
        metrics: env.AZURE_LIVE_METRICS_CACHE_TTL_MS,
        alerts: env.AZURE_MONITOR_ALERTS_CACHE_TTL_MS,
        appInsights: env.AZURE_APP_INSIGHTS_CACHE_TTL_MS,
        trafficAnalytics: env.AZURE_TRAFFIC_ANALYTICS_CACHE_TTL_MS,
        nsgFlowLogs: env.AZURE_NSG_FLOW_LOG_CACHE_TTL_MS,
        connectionMonitor: env.AZURE_CONNECTION_MONITOR_CACHE_TTL_MS,
      },
    });
  });
}

/** Check if the snapshot has any resolved metrics (not all zeros/empty) */
function hasRealData(snapshot: ReturnType<typeof generateMockSnapshot>): boolean {
  const { topology } = snapshot;
  return (topology?.resolvedBindings ?? 0) > 0;
}

/** Tag a snapshot with its data source for frontend debugging */
function withSource<T extends Record<string, unknown>>(
  data: T,
  source: "azure" | "mock",
  error?: string,
): T & { _source: string; _error?: string } {
  return { ...data, _source: source, ...(error ? { _error: error } : {}) };
}
